baseURL: "https://www.luchtgomtechniek.be/"
title: Luchtgomtechniek
relativeURLs: false
disableKinds:
  - section
  - taxonomy
  - RSS
disableHugoGeneratorInject: true
enableGitInfo: true
enableRobotsTXT: true
defaultContentLanguage: nl
defaultContentLanguageInSubdir: true
timeout: 60000
