fr:
  weight: 2
  languageName: Français
  title: Technique d'aérogommage - Restauration et rénovation professionnelles du bois et de la pierre
  params:
    description: Faire aérogommer votre escalier, façade ou vos meubles par des professionnels ? Technique d'aérogommage restaure le bois et la pierre avec précision. Découvrez nos réalisations et demandez un devis gratuit !
    keywords: aérogommage, restauration, rénovation, restauration du bois, restauration de la pierre, cage d'escalier, façade, pierre bleue, cèdre, savoir-faire, patrimoine, finition moderne
nl:
  weight: 1
  languageName: Nederlands
  title: Luchtgomtechniek - Professionele restauratie en renovatie van hout en steen
  params:
    description: Uw trap, gevel of meubels professioneel laten luchtgommen? Luchtgomtechniek herstelt hout en steen met precisie en vakmanschap in regio Limburg en Luik. Bekijk onze realisaties en vraag een gratis offerte aan!
    keywords: luchtgommen, restauratie, renovatie, houtrestauratie, steenrestauratie, trappenhuis, gevel, blauwsteen, ceder, vakmanschap, erfgoed, moderne afwerking
