fr:
  weight: 2
  languageName: Français
  title: l'aérogommage, sablage fin, microbillage aux perles de verre, peinture à poudre - L'aerogommage
  params:
    description: Pour l'Aérogommage de tous types de bois, le sablage fin du fer, le microbillage de l'acier inoxydable,  le sablage de la beton et les petits travaux spécialisés de peinture de poudre.
    keywords: l'aérogommage, sablage fin, microbillage, nettoyage, billage de verre, bicarbonate, pulvérisation, dérouillage, polissage
nl:
  weight: 1
  languageName: Nederlands
  title: luchtgommen, fijn zandstralen, glasparelstralen, poedercoaten - Luchtgomtechniek
  params:
    description: Voor het luchtgommen van alle soorten en types hout, fijnstralen van ijzerwerk, glasparelstralen van inox, betonstralen en gespecialiseerd poedercoatwerk.
    keywords: luchtgommen, fijn zandstralen, glasparelstralen, poedercoaten, zandstralen, reinigen, bicarbonaat, spuiten, roest verwijderen, polijsten
