fr:
  weight: 2
  languageName: Français
  title: Technique d'aérogommage - Restauration et rénovation professionnelles du bois et de la pierre
  params:
    description: Découvrez l'expertise de Technique d'aérogommage dans la restauration et la rénovation du bois et de la pierre. Des cages d'escalier aux façades, nous restaurons la beauté authentique avec précision et savoir-faire.
    keywords: aérogommage, restauration, rénovation, restauration du bois, restauration de la pierre, cage d'escalier, façade, pierre bleue, cèdre, savoir-faire, patrimoine, finition moderne
nl:
  weight: 1
  languageName: Nederlands
  title: Luchtgomtechniek - Professionele restauratie en renovatie van hout en steen
  params:
    description: Ontdek de expertise van Luchtgomtechniek in het restaureren en renoveren van hout en steen. Van trappenhuizen tot gevels, wij herstellen de authentieke schoonheid met precisie en vakmanschap.
    keywords: luchtgommen, restauratie, renovatie, houtrestauratie, steenrestauratie, trappenhuis, gevel, blauwsteen, ceder, vakmanschap, erfgoed, moderne afwerking
