mounts:
  - source: node_modules/jquery/dist
    target: assets/jquery
  - source: node_modules/jquery-bridget
    target: assets/jquery-bridget
  - source: node_modules/swiper
    target: assets/swiper
  - source: assets
    target: assets
  - source: node_modules/@fontsource/open-sans
    target: static/css
  - source: node_modules/@fontsource/roboto-slab
    target: static/css
  - source: node_modules/@fontsource/oswald
    target: static/css
  - source: static
    target: static
