[build]
command = "yarn run build"
publish = "public"

[build.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"
NODE_VERSION = "18.2.0"

[[redirects]]
  from = "/"
  to = "/fr/"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/nl/"
  status = 302
  force = true

[[redirects]]
  from = "http://www.straalatelier.com/*"
  to = "https://www.luchtgomtechniek.be/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.straalatelier.com/*"
  to = "https://www.luchtgomtechniek.be/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://straalatelier.eu/*"
  to = "https://www.luchtgomtechniek.be/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://straalatelier.eu/*"
  to = "https://www.luchtgomtechniek.be/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public,max-age=14400"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public,max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public,max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

# Context switches below

[context.deploy-preview]
  command = "yarn run build --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "yarn run build -b $DEPLOY_PRIME_URL"

[context.production]
  [[context.production.plugins]]
    package = "netlify-plugin-submit-sitemap"

  [[context.production.plugins]]
    package = "netlify-plugin-checklinks"

  [[context.production.plugins]]
    package = "netlify-plugin-hugo-cache-resources"
