[build]
  publish = "public/"
  command = "hugo --gc --minify"

  [build.environment]
    HUGO_VERSION = "0.92.2"
    HUGO_ENV = "production"
    NODE_VERSION = "16.5.0"
    NODE_ENV = "production"


# Context switches below

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.101.0"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.101.0"


[context.production]
  command = "hugo --gc --minify"
  [context.production.environment]
    HUGO_ENABLEGITINFO = "true"
    HUGO_ENV = "production"
    HUGO_VERSION = "0.92.2"
    NETLIFY_USE_YARN = "true"

  [[context.production.plugins]]
    package = "netlify-plugin-checklinks"

  [[context.production.plugins]]
    package = "netlify-plugin-hugo-cache-resources"

  [[context.production.plugins]]
    package = "netlify-plugin-submit-sitemap"

[[edge_functions]]
  path = "/test"
  function = "hello"
