[build]
  publish = "public"
  command = "yarn build"

  [build.environment]
    HUGO_VERSION = "0.121.2"
    HUGO_ENV = "production"
    NODE_VERSION = "19.6.0"
    NODE_ENV = "production"

[[headers]]
  for = "/*/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public,max-age=14400"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public,max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public,max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"

# Context switches below

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.121.2"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.121.2"

[context.production]
  command = "hugo --gc --minify"
  [context.production.environment]
    HUGO_ENABLEGITINFO = "true"
    HUGO_ENV = "production"
    HUGO_VERSION = "0.121.2"
    NETLIFY_USE_YARN = "true"

  [[context.production.plugins]]
    package = "netlify-plugin-checklinks"

  [[context.production.plugins]]
    package = "netlify-plugin-hugo-cache-resources"
